# Generated by Django 5.0.1 on 2024-02-07 19:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="avatar",
            field=models.ImageField(
                default="media\\default_avatar.png", upload_to="media\\profile_images"
            ),
        ),
    ]
